### ISSUE TITLE
Can't find bash ./scripts/pull.sh

### ISSUE THREAD

**Issue by TahaBinhuraib** [sapientml/docs#4]
I downloaded the following zip but could not find a pull.sh file
wget https://github.com/sapientml/sapientml/files/12593737/sapientml-corpus-0.1.0.zip

**Comment by TahaBinhuraib** [comment]
Also, it would be great if you could point me to the script used to download the data from kaggle.

**Comment by kimusaku** [comment]
@TahaBinhuraib thanks for raising the issue.
We updated the corpus and the documentation.

https://github.com/sapientml/docs/files/13290907/sapientml-corpus-0.1.1.zip
includes `./scripts/pull.sh`, a script for downloading datasets from Kaggle.

Thanks again for your contribution!

**Comment by kimusaku** [comment]
We have updated the corpus and documentation again.
Please use the following file:
https://github.com/sapientml/sapientml/files/13360498/sapientml-corpus-0.1.2.zip

**Comment by TahaBinhuraib** [comment]
Thank you very much!
